language: php
node_js:
- "7"
php:
- 7.0
before_script:
- cp app/config/parameters.yml.travis app/config/parameters.yml
- composer install
- php bin/console doctrine:database:create --env=test
- php bin/console doctrine:schema:create --env=test
- php bin/console faker:populate --env=test
- . $HOME/.nvm/nvm.sh
- nvm install stable
- nvm use stable
- npm install
- npm --version
- node --version
- npm list --depth=0
- npm rebuild node-sass;
- npm run build
script:
- "./vendor/bin/phpunit"
before_deploy:
- openssl aes-256-cbc -K $encrypted_caea40e6cd40_key -iv $encrypted_caea40e6cd40_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
