# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@a
    updateModifierUserListener:
        class: AppBundle\EventListener\updateModifierUser
        arguments: ["@security.token_storage"]
        tags:
          - { name: doctrine.event_listener, event : prePersist}
    generatePlaceCoordinatesListener:
        class: AppBundle\EventListener\GeneratePlaceCoordinates
        tags:
          - { name: doctrine.event_listener, event : prePersist}
    GeneratePlaceImage:
        class: AppBundle\EventListener\GeneratePlaceImage
        tags:
          - { name: doctrine.event_listener, event : prePersist}
    getData:
        class: AppBundle\Command\GetData
        arguments: ["@doctrine.orm.entity_manager"]
    faker.provider.place_provider:
        class: AppBundle\Provider\PlaceProvider
        arguments: ["@faker.generator"]
        tags:
            - { name: bazinga_faker.provider }
    infoProvider:
        class: AppBundle\Service\InfoProvider
        arguments: ["@doctrine.orm.entity_manager"]
    testUser:
        class: AppBundle\Service\TestUser
        arguments: ["@doctrine.orm.entity_manager"]
